# Generated by Django 4.2.1 on 2023-06-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0006_alter_quiz_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('hard', 'hard'), ('easy', 'easy'), ('medium', 'medium')], max_length=120),
        ),
    ]
