# Generated by Django 4.2.1 on 2023-06-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='category',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='text',
        ),
    ]
